#------------project configuration start----------------#
openie_llm: &openie_llm
  api_key:
  base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
  model: deepseek-v3
  type: maas

chat_llm: &chat_llm
  api_key:
  base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
  model: deepseek-v3
  type: maas

vectorize_model: &vectorize_model
  api_key:
  base_url: https://api.siliconflow.cn/v1/
  model: BAAI/bge-m3
  type: openai
  vector_dimensions: 1024
vectorizer: *vectorize_model

log:
  level: INFO

project:
  biz_scene: default
  host_addr: http://127.0.0.1:8887
  id: '1'
  language: en
  namespace: AISearch
#------------project configuration end----------------#

#------------kag-builder configuration start----------------#
kag_builder_pipeline:
  chain:
    type: unstructured_builder_chain # kag.builder.default_chain.DefaultUnstructuredBuilderChain
    extractor:
      type: event_extractor # kag.builder.component.extractor.schema_free_extractor.SchemaFreeExtractor
      llm: *openie_llm
    reader:
      type: aisearch_txt_reader # kag.builder.component.reader.dict_reader.DictReader
    post_processor:
      type: event_post_processor # kag.builder.component.postprocessor.kag_postprocessor.KAGPostProcessor
      similarity_threshold: 0.9
    splitter:
      type: length_splitter_event # kag.builder.component.splitter.length_splitter.LengthSplitter
      split_length: 1000
      window_length: 0
    vectorizer:
      type: batch_vectorizer # kag.builder.component.vectorizer.batch_vectorizer.BatchVectorizer
      vectorize_model: *vectorize_model
    writer:
      type: kgfabric_writer # kag.builder.component.writer.kg_writer.KGWriter
      url : http://6.3.176.118:8888/v1/kgfabric/namespace/kg_event_test/
  num_threads_per_chain: 1
  num_chains: 10
  scanner:
    type: csv_scanner # kag.builder.component.scanner.dataset_scanner.MusiqueCorpusScanner
    col_names: [pid, text]
    delimiter: "\t"
#------------kag-builder configuration end----------------#

#------------kag-solver configuration start----------------#
naive_chunk_retriever: &naive_chunk_retriever
  type: naive_kag_fr_retriever # kag.solver.retriever.impl.default_fuzzy_kg_retriever.DefaultFuzzyKgRetriever
  llm_client: *chat_llm
  recall_num: 10
  rerank_topk: 10

kag_solver_pipeline:
  memory:
    type: default_memory # kag.solver.implementation.default_memory.DefaultMemory
    llm_client: *chat_llm
  retriever: *naive_chunk_retriever
  generator:
    type: default_generator # kag.solver.implementation.default_generator.DefaultGenerator
    llm_client: *chat_llm
    generate_prompt:
      type: default_resp_generator # kag.solver.prompt.default.resp_generator.RespGenerator

#------------kag-solver configuration end----------------#
