name: Documentation Related
description: Suggest an improvement or report a bug for this project's Documentation
title: "[Doc][Module Name] Documentation bug or improvement"
labels: [ "documentation", "Waiting for reply" ]
body:
  - type: markdown
    attributes:
      value: >
        Thank you for taking the time to suggest an improvement or report a bug for this project's documentation. 
        The `[Module Name]` in title see [here](https://github.com/OpenSPG/KAG/labels), 
        if you don't know the module name, you don't have to fill it in.

  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please make sure to search in the [issues](https://github.com/OpenSPG/KAG/issues?q=is%3Aissue) first
        to see whether the same feature was requested already.
      options:
        - label: >
            I had searched in the [issues](https://github.com/OpenSPG/KAG/issues?q=is%3Aissue) and found no
            similar feature requirement.
          required: true

  - type: textarea
    attributes:
      label: Description
      description: A short description why your find in our document.

  - type: textarea
    attributes:
      label: Documentation Links
      description: Copy and paste one or more links of this documentation issue.


  - type: checkboxes
    attributes:
      label: Are you willing to submit PR?
      description: >
        It's completely optional, but if you're interested in contributing, we're here to help! 
        If you have insights on the solution, that's even better. KAG thrives on community support, 
        and we warmly welcome new contributors.
      options:
        - label: Yes I am willing to submit a PR!

  - type: markdown
    attributes:
      value: "Thanks for completing our form!"