# coding: utf-8
# Copyright 2023 OpenSPG Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied.

"""
    knext

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from knext.common.rest.configuration import Configuration


class RefDoc(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        "id": "str",
        "content": "str",
        "document_id": "str",
        "document_name": "str",
        "url": "str",
    }

    attribute_map = {
        "id": "id",
        "content": "content",
        "document_id": "document_id",
        "document_name": "document_name",
        "url": "url",
    }

    def __init__(
        self,
        id=None,
        content=None,
        document_id=None,
        document_name=None,
        url=None,
        local_vars_configuration=None,
    ):  # noqa: E501
        """RefDoc - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._content = None
        self._document_id = None
        self._document_name = None
        self._url = None
        self.discriminator = None

        self.id = id
        self.content = content
        self.document_id = document_id
        self.document_name = document_name
        if url is not None:
            self.url = url

    @property
    def id(self):
        """Gets the id of this RefDoc.  # noqa: E501


        :return: The id of this RefDoc.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this RefDoc.


        :param id: The id of this RefDoc.  # noqa: E501
        :type: str
        """
        if (
            self.local_vars_configuration.client_side_validation and id is None
        ):  # noqa: E501
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def content(self):
        """Gets the content of this RefDoc.  # noqa: E501


        :return: The content of this RefDoc.  # noqa: E501
        :rtype: str
        """
        return self._content

    @content.setter
    def content(self, content):
        """Sets the content of this RefDoc.


        :param content: The content of this RefDoc.  # noqa: E501
        :type: str
        """
        if (
            self.local_vars_configuration.client_side_validation and content is None
        ):  # noqa: E501
            raise ValueError(
                "Invalid value for `content`, must not be `None`"
            )  # noqa: E501

        self._content = content

    @property
    def document_id(self):
        """Gets the document_id of this RefDoc.  # noqa: E501


        :return: The document_id of this RefDoc.  # noqa: E501
        :rtype: str
        """
        return self._document_id

    @document_id.setter
    def document_id(self, document_id):
        """Sets the document_id of this RefDoc.


        :param document_id: The document_id of this RefDoc.  # noqa: E501
        :type: str
        """
        if (
            self.local_vars_configuration.client_side_validation and document_id is None
        ):  # noqa: E501
            raise ValueError(
                "Invalid value for `document_id`, must not be `None`"
            )  # noqa: E501

        self._document_id = document_id

    @property
    def document_name(self):
        """Gets the document_name of this RefDoc.  # noqa: E501


        :return: The document_name of this RefDoc.  # noqa: E501
        :rtype: str
        """
        return self._document_name

    @document_name.setter
    def document_name(self, document_name):
        """Sets the document_name of this RefDoc.


        :param document_name: The document_name of this RefDoc.  # noqa: E501
        :type: str
        """
        if (
            self.local_vars_configuration.client_side_validation
            and document_name is None
        ):  # noqa: E501
            raise ValueError(
                "Invalid value for `document_name`, must not be `None`"
            )  # noqa: E501

        self._document_name = document_name

    @property
    def url(self):
        """Gets the url of this RefDoc.  # noqa: E501


        :return: The url of this RefDoc.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this RefDoc.


        :param url: The url of this RefDoc.  # noqa: E501
        :type: str
        """

        self._url = url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RefDoc):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, RefDoc):
            return True

        return self.to_dict() != other.to_dict()

    def __hash__(self):
        return hash(tuple(sorted(self.to_dict().items())))
