llm: &id001
  api_key: key
  base_url: https://api.deepseek.com
  model: deepseek-chat
  type: maas
log:
  level: INFO

project:
  biz_scene: default
  host_addr: http://127.0.0.1:8887
  id: '8'
  language: en
  namespace: CsQa

runner:
  chain:
    extractor:
      llm: *id001
      ner_prompt:
        type: default_ner
      std_prompt:
        type: default_std
      triple_prompt:
        type: default_triple
      type: schema_free
    reader:
      type: txt
    post_processor:
      similarity_threshold: 0.9
      type: base
    splitter:
      split_length: 4950
      type: length
      window_length: 100
    type: unstructured
    vectorizer:
      type: batch
      vectorize_model: &id002
        api_key: key
        base_url: https://api.siliconflow.cn/v1/
        model: BAAI/bge-m3
        type: openai
        vector_dimensions: 1024
    writer:
      type: kg
  num_threads_per_chain: 50
  num_chains: 16
  scanner:
    type: dir
vectorize_model: *id002
vectorizer: *id002

lf_solver_pipeline:
  memory: default_memory
  max_iterations: 3
  generator:
    type: default_generator
    generate_prompt:
      type: default_resp_generator
  reflector:
    type: default_reflector
  reasoner:
    type: default_reasoner
    lf_planner:
      type: default_lf_planner
    lf_executor:
      type: default_lf_executor
      force_chunk_retriever: true
      exact_kg_retriever:
        type: default_exact_kg_retriever
        el_num: 5
        search_api: &id003
          type: openspg_search_api
        graph_api: &id004
          type: openspg_graph_api
      fuzzy_kg_retriever:
        type: default_fuzzy_kg_retriever
        el_num: 5
        vectorize_model: *id002
        llm_client: *id001
        search_api: *id003
        graph_api: *id004
      chunk_retriever: &id005
        type: default_chunk_retriever
        recall_num: 10
        rerank_topk: 10
      merger:
        type: default_lf_sub_query_res_merger
        chunk_retriever: *id005
