name: License Checker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check:
    name: "License Validation"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Check License Header
        uses: apache/skywalking-eyes@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          log: info
      - name: Check Dependencies' License
        uses: apache/skywalking-eyes/dependency@main