# -*- coding: utf-8 -*-
# Copyright 2023 OpenSPG Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied.
from abc import ABC, abstractmethod
from typing import List

from kag.interface.builder.base import BuilderComponent
from kag.builder.model.chunk import Chunk
from knext.common.base.runnable import Input, Output


class RecordParserABC(BuilderComponent, ABC):
    """
    Abstract base class for parsing records generated by upstream reader into a list of text chunks.

    This class defines the interface for components that parse records generated by upstream readers
    and convert them into a list of text chunks. It inherits from `BuilderComponent` and `ABC` (Abstract Base Class).
    """

    @property
    def input_types(self) -> Input:
        return str

    @property
    def output_types(self) -> Output:
        return Chunk

    @abstractmethod
    def invoke(self, input: Input, **kwargs) -> List[Output]:
        """
        Abstract method to invoke the parser to process input data.

        This method must be implemented by any subclass. It is responsible for processing the input data
        and generating a list of output results, typically containing text chunks.

        Args:
            input (Input): Input data containing records to be parsed.
            **kwargs: Additional keyword arguments.

        Returns:
            List[Output]: A list of processed results, containing text chunks.

        Raises:
            NotImplementedError: If the method is not implemented in the subclass.
        """
        raise NotImplementedError(
            f"`invoke` is not currently supported for {self.__class__.__name__}."
        )
